
services:
  chagpt-ui:
    image: ghcr.io/zaki-1052/gptportal:latest
    volumes:
      - ./.env:/app/.env #env variables for the app
      # - ./public/instructions.md:/app/public/instructions.md # OPTIONAL customize the system prompt
      # - ./public/claudeInstructions.xml:/app/public/claudeInstructions.xml # OPTIONAL customize Claude instructions

    ports:
      - 3000:3000
